/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechStack: typeof import('./src/components/homepage/TechStack.vue')['default']
    TheFooter: typeof import('./src/components/homepage/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/homepage/TheHeader.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
  }
}
